# Uncomment the next line to define a global platform for your project
 platform :ios, '18.2'

target 'CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'

  # Pods for CocoaPods

end
